name: CI Pipeline

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: PostDatabaseTest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Commit Lint
        uses: wagoid/commitlint-github-action@v4

      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        run: mvn -B test
        env:
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: admin
          DATABASE_DOMAIN: localhost
          DATABASE_SHEMA: PostDatabaseTest
          DATABASE_PORT: 5432

      - name: Cache SonarCloud Packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Analyze With SonarCloud
        run: mvn -B verify -Pcoverage sonar:sonar -Dsonar.projectKey=DISLINKT-ORGANIZATION_dl-post-dislinkt.postservice.service -Dsonar.organization=dislinkt-organization -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: admin
          DATABASE_DOMAIN: localhost
          DATABASE_SHEMA: PostDatabaseTest
          DATABASE_PORT: 5432

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 40
#          min-coverage-changed-files: 60